import { pgEnum } from "drizzle-orm/pg-core";

export const createAccessibilitySetup = (deps: Record<string, any>) => {
  const adminOnlyTables = {
    brands: deps.brands,
    brandsOnStates: deps.brandsOnStates,
    brandsOnCities: deps.brandsOnCities,
    brandsOnAreas: deps.brandsOnAreas,
    propertyTypes: deps.propertyTypes,
    activities: deps.activities,
    activitiesOnProperties: deps.activitiesOnProperties,
    amenities: deps.amenities,
    amenitiesOnProperties: deps.amenitiesOnProperties,
    safetyHygiene: deps.safetyHygiene,
    safetyHygieneOnProperties: deps.safetyHygieneOnProperties,
    states: deps.states,
    cities: deps.cities,
    areas: deps.areas,
    landmarks: deps.landmarks,
    nearbyLocations: deps.nearbyLocations,
    admins: deps.admins,
    adminPermissions: deps.adminPermissions,
    adminRolePermissions: deps.adminRolePermissions,
    settings: deps.settings,
    cancellationPlans: deps.cancellationPlans,
    specialDates: deps.specialDates,
    cancellationPercentages: deps.cancellationPercentages,
    tags: deps.tags,
    propertyTags: deps.propertyTags,
    cms: deps.cms,
    carousel: deps.carousel,
    carouselPhotos: deps.carouselPhotos,
    collections: deps.collections,
    collectionProperties: deps.collectionProperties,
    spaces: deps.spaces,
    extraPlans: deps.extraPlans,
    faqs: deps.faqs,
    bookingAuditLog: deps.bookingAuditLog,
    staticImages: deps.staticImages,
  } as const;

  const userAccessibleTables = {
    proposals: deps.proposals,
    proposalItems: deps.proposalItems,
    users: deps.users,
    ownersOnProperties: deps.ownersOnProperties,
    managersOnProperties: deps.managersOnProperties,
    caretakersOnProperties: deps.caretakersOnProperties,
    properties: deps.properties,
    propertiesDataSpecificToBrands: deps.propertiesDataSpecificToBrands,
    splitPropertyMappings: deps.splitPropertyMappings,
    mergedPropertyMappings: deps.mergedPropertyMappings,
    icalLinks: deps.icalLinks,
    importedBookings: deps.importedBookings,
    customers: deps.customers,
    bookingPricing: deps.bookingPricing,
    bookingDiscounts: deps.bookingDiscounts,
    bookingCancellation: deps.bookingCancellation,
    bookingRefund: deps.bookingRefund,
    bookings: deps.bookings,
    bookingGuests: deps.bookingGuests,
    bookingRequests: deps.bookingRequests,
    bookingPayments: deps.bookingPayments,
    discountPlans: deps.discountPlans,
    discountPlansValues: deps.discountPlansValues,
    coupons: deps.coupons,
    propertyCoupons: deps.propertyCoupons,
    propertyDiscountPlans: deps.propertyDiscountPlans,
    propertyCancellationPlans: deps.propertyCancellationPlans,
    blocking: deps.blocking,
    inventoryCalendar: deps.inventoryCalendar,
    reviews: deps.reviews,
    reviewMagicLinks: deps.reviewMagicLinks,
    photos: deps.photos,
    photoPropertyBrandMapping: deps.photoPropertyBrandMapping,
    enquiries: deps.enquiries,
    spaceProperties: deps.spaceProperties,
    contactEnquiry: deps.contactEnquiry,
    viewEnquiry: deps.viewEnquiry,
    searchQuery: deps.searchQuery,
    whatsappLog: deps.whatsappLog,
    globalConstants: deps.globalConstants,
    bookingPaymentSchedule: deps.bookingPaymentSchedule,
    platformLedger: deps.platformLedger,
    propertyCommissionMilestones: deps.propertyCommissionMilestones,
    propertyMilestoneResults: deps.propertyMilestoneResults,
    ownerWallet: deps.ownerWallet,
    ownerSettlement: deps.ownerSettlement,
    ownerWalletLedger: deps.ownerWalletLedger,
    ownerPayouts: deps.ownerPayouts,
    supervisors: deps.supervisors,
    propertyAuditAreaCategoryMaster: deps.propertyAuditAreaCategoryMaster,
    propertyAuditAreas: deps.propertyAuditAreas,
    checklistCategoryMaster: deps.checklistCategoryMaster,
    checklistItemMaster: deps.checklistItemMaster,
    issueTypes: deps.issueTypes,
    inventoryChecklistItems: deps.inventoryChecklistItems,
    suppliesChecklistItems: deps.suppliesChecklistItems,
    maintenanceChecklistItems: deps.maintenanceChecklistItems,
    propertyAuditSessions: deps.propertyAuditSessions,
    inventoryAuditChecklistItems: deps.inventoryAuditChecklistItems,
    suppliesAuditChecklistItems: deps.suppliesAuditChecklistItems,
    maintenanceAuditChecklistItems: deps.maintenanceAuditChecklistItems,
    checklistItemMedia: deps.checklistItemMedia,
    tickets: deps.tickets,
    ticketResolutionLogs: deps.ticketResolutionLogs,
  } as const;

  const allTables = {
    ...userAccessibleTables,
    ...adminOnlyTables,
  } as const;

  return {
    adminOnlyTables,
    userAccessibleTables,
    allTables,
  };
};

export const createTableNameEnum = (allTables: Record<string, unknown>) =>
  pgEnum("tableNameEnum", Object.keys(allTables) as [string, ...string[]]);
